### ISSUE TITLE
How to run cargo test with the simple_boot example?

### ISSUE THREAD

**Issue by vityafx** [rust-osdev/bootloader#193]
How can I run the cargo test using the `simple_boot` example?
I have the `krun`, `kimage` and `kbuild` aliases in my `.cargo/config` file but how do I write one for testing?

```toml
[target.'cfg(target_os = "none")']
runner = "cargo run --package simple_boot --"

[alias]
kbuild = "build --target x86_64-my_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target x86_64-my_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem -- --no-run"
krun = "run --target x86_64-my_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
```

I am basically following the blog post and, of course, it doesn't work: https://os.phil-opp.com/testing/
