### ISSUE TITLE
panic on large memory regions when `map-physical-memory` is enabled

### ISSUE THREAD

**Issue by hawkw** [rust-osdev/bootloader#262]
Trying to test out a higher half kernel using PR #229, the bootloader panics when the `map-physical-memory`, `map-framebuffer`, and `dynamic-range-start` configurations are all present.

I have the following configurations in my `Cargo.toml`:
```toml
[package.metadata.bootloader]
map-physical-memory = true
# the kernel is mapped into the higher half of the virtual address space.
dynamic-range-start = "0xFFFF_8000_0000_0000"

[patch.crates-io]
# patch `bootloader` to use https://github.com/rust-osdev/bootloader/pull/229
# for dynamic range address configuration support.
#
# remove this patch once rust-osdev/bootloader#229 makes it into a release
# version.
bootloader = { git = "https://github.com/rust-osdev/bootloader", rev = "ac46d0455b41c11e5d316348d068df1c495ce0af" }
```

I get the following panic:
https://github.com/rust-osdev/bootloader/blob/ac46d0455b41c11e5d316348d068df1c495ce0af/src/binary/mod.rs#L355
which fails on a `ParentEntryHugeFrame` error:
![image](https://user-images.githubusercontent.com/2796466/191811790-819efd18-f8d4-4ba0-8d15-45ac4cf2ef74.png)

**Comment by hawkw** [comment]
When the `map-page-table-recursively` setting is also `true`, there's a different panic while setting up the recursive mapping:
![image](https://user-images.githubusercontent.com/2796466/191813883-5cf3ef88-1486-4123-8bdc-c05aee501657.png)

```toml
[package.metadata.bootloader]
map-physical-memory = true
map-page-table-recursively = true
dynamic-range-start = "0xFFFF_8000_0000_0000"
```
