### ISSUE TITLE
bootloader 0.11.0 build error

### ISSUE THREAD

**Issue by Choi-Jungwoo** [rust-osdev/bootloader#298]
# RUSTC

rustc 1.68.0-nightly (0f529f0f4 2022-12-13)
binary: rustc
commit-hash: 0f529f0f49f4dd404b78e605398531c96f220fc5
commit-date: 2022-12-13
host: x86_64-pc-windows-msvc
release: 1.68.0-nightly
LLVM version: 15.0.6

# RUN

```cmd
cargo bootimage
```

# ERROR

![image](https://user-images.githubusercontent.com/26923066/208154922-605ac6cd-b866-4adb-b342-6e314b69dd9d.png)

# DEPENDENCIES

```toml
[dependencies]
bootloader = "0.11.0"
```

# SUCCESSFLLY BUILD VERSION

```toml
[dependencies]
bootloader ="0.9.23"
```

![image](https://user-images.githubusercontent.com/26923066/208155836-36ca4b22-af14-49ae-8f93-83b394ce1e8c.png)
