### ISSUE TITLE
thread 'main' panicked at 'no entry found for key', src\tools\cargo\src/cargo\core\compiler\unit_dependencies.rs

### ISSUE THREAD

**Issue by LovesAsuna** [rust-osdev/bootloader#329]
As you submitted the [issue](https://github.com/rust-lang/cargo/issues/10444) earlier，I don't know how to solve this problem.

**Comment by phil-opp** [comment]
Could you clarify what you're trying to do and how this is related to the `bootloader` crate?

**Comment by LovesAsuna** [comment]
I am now migrating from bootloader v0.9.X to bootloader v0.11. I follow the guide and  use the build script to build kernel.But ran into the problem I mentioned above.

---

In the root package, I created a `config.toml`

```toml
[unstable]
bindeps = true
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-simple_os.json"
```

In the root package, the `Cargo.toml` is

```toml
[package]
name = "simple_os"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bootloader = "0.11"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none"}

[workspace]
members = ["kernel"]
```

In the kernel package, I created a `config.toml` as well

```toml
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-simple_os.json"
```

The problem is that when I execute command `Cargo build`, the error occurs.

![SW0FWSFZ8IN4DZ75_PSMIEO](https://user-images.githubusercontent.com/32810896/213702556-6dbe0c75-33af-449a-8900-f6026464b4eb.png)

---

By the way, I've tried leaving only `bindeps` option in the root package's `config.toml`.Then the error would be

![FH~UF(7ET%N%BA53PK8KHI0](https://user-images.githubusercontent.com/32810896/213702567-2730147e-40f8-40f8-a18a-fc6e597d68e4.png)
