### ISSUE TITLE
Can't compile the bootloader

### ISSUE THREAD

**Issue by Milk-Cool** [rust-osdev/bootloader#441]
Hi!

The error is:
```
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-lowos` target may not support the standard library
  = note: `std` is required by `ovmf_prebuilt` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```
The kernel is pretty much `blog_os` which you are probably already familiar with.

`/Cargo.toml`:
```toml
[package]
name = "lowos-wrapper"
version = "0.1.0"

[build-dependencies]
bootloader = "0.11"
lowos = { path = "lowos", artifact = "bin", target = "./lowos/x86_64-lowos.json" }

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"

[workspace]
members = ["lowos"]
```
`/.cargo/config.toml`
```toml
[unstable]
# enable the unstable artifact-dependencies feature, see
# https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#artifact-dependencies
bindeps = true
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "lowos/x86_64-lowos.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
```
`/lowos/.cargo/config.toml`
```toml
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-lowos.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
```
Other files are just like in the template.

System: Ubuntu 23.10

**Comment by Freax13** [comment]
Try removing the `target` key from `.cargo/config.toml`. You only want to compile `lowos` using your target, you don't want `lowos-wrapper` and its dependencies (including `ovmf_prebuilt`) to use this target.

**Comment by Milk-Cool** [comment]
Yes, but here it says that a target is needed to recompile `std`. 
```
error: -Zbuild-std requires --target
```
If I don't recompile `std`, then it won't install some required packages with this error:
```
error[E0463]: can't find crate for `core`
...
error[E0463]: can't find crate for `std`
```

**Comment by Freax13** [comment]
Try passing `--target x86_64-unknown-linux-gnu`. AFAICT, as of right now bindeps and custom targets (-> build-std), don't play very well together, so passing the target explicitly is required.

Depending on your use case, you might be able to use `x86_64-unknown-none` for `lowos`. `x86_64-unknown-none` doesn't need build-std.

**Comment by Milk-Cool** [comment]
I want to build an image to run something that I shamelessly copy-pasted on real hardware.

Also, if I add `--target x86_64-unknown-linux-gnu` (or `--target x86_64-unknown-none`, idk what you meant to put here) to either `cargo run` or `cargo build`, it prints the following error:
```
thread 'main' panicked at src/cargo/core/compiler/unit_dependencies.rs:178:34:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Milk-Cool** [comment]
found this: https://github.com/rust-lang/cargo/issues/10444

still open, is there maybe a workaround for this issue?

**Comment by Freax13** [comment]
> found this: [rust-lang/cargo#10444](https://github.com/rust-lang/cargo/issues/10444)

Yup, I was about to say that as well.

> still open, is there maybe a workaround for this issue?

No, there isn't, but you don't need this.

You seem to have mixed the files meant to be used with older versions of the bootloader with files meant for the current version. Try the following steps:
1. Delete `/lowos/.cargo/config.toml`.
2. Replace `/.cargo/config.toml` with just
```toml
[unstable]
# enable the unstable artifact-dependencies feature, see
# https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#artifact-dependencies
bindeps = true
```
3. Replace `lowos = { path = "lowos", artifact = "bin", target = "./lowos/x86_64-lowos.json" }` with `lowos = { path = "lowos", artifact = "bin", target = "x86_64-unknown-none }`

**Comment by Milk-Cool** [comment]
I followed your steps, and got the following error:
```
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-none` target may not support the standard library
  = note: `std` is required by `ovmf_prebuilt` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```
So I added `build-std = ["core", "compiler_builtins"]` to `/.cargo/config.toml`. (I also tried `cargo build -Zbuild-std=core,compiler_builtins`.) Then I got
```
error: -Zbuild-std requires --target
```
So I added
```toml
[build]
target = "x86_64-unknown-none"
```
to `config.toml`, and I got the same error as before:
```
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-none` target may not support the standard library
  = note: `std` is required by `ovmf_prebuilt` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```
A little confused here...

**Comment by Freax13** [comment]
Please undo

> I followed your steps, and got the following error:
> 
> ```
> error[E0463]: can't find crate for `std`
>   |
>   = note: the `x86_64-unknown-none` target may not support the standard library
>   = note: `std` is required by `ovmf_prebuilt` because it does not declare `#![no_std]`
>   = help: consider building the standard library from source with `cargo build -Zbuild-std`
> ```
> 
> So I added `build-std = ["core", "compiler_builtins"]` to `/.cargo/config.toml`. (I also tried `cargo build -Zbuild-std=core,compiler_builtins`.) Then I got

this

> ```
> error: -Zbuild-std requires --target
> ```
> 
> So I added
> 
> ```toml
> [build]
> target = "x86_64-unknown-none"
> ```
> 
> to `config.toml`, and I got the same error as before:

and this.

> ```
> error[E0463]: can't find crate for `std`
>   |
>   = note: the `x86_64-unknown-none` target may not support the standard library
>   = note: `std` is required by `ovmf_prebuilt` because it does not declare `#![no_std]`
>   = help: consider building the standard library from source with `cargo build -Zbuild-std`
> ```
> 
> A little confused here...

What command are you using to build/run the kernel?

**Comment by Milk-Cool** [comment]
> What command are you using to build/run the kernel?
`cargo build`, though `cargo run` doesn't work either

**Comment by Freax13** [comment]
Is that the whole command or are you adding additional arguments (e.g. `--target x86_64-unknown-none`)?

**Comment by Milk-Cool** [comment]
Yep, that's the whole command, though I have tried `cargo build -Zbuild-std=core,compiler_builtins --target=x86_64-unknown-none`

**Comment by Freax13** [comment]
That's odd. Could you repeat the content of your files?

**Comment by Milk-Cool** [comment]
`/Cargo.toml`
```toml
[package]
name = "lowos-wrapper"
version = "0.1.0"

[build-dependencies]
bootloader = "0.11"
lowos = { path = "lowos", artifact = "bin", target = "x86_64-unknown-none" }

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"

[workspace]
members = ["lowos"]
```
`/lowos/Cargo.toml`
```toml
[package]
name = "lowos"
version = "0.1.0"
edition = "2018"

[dependencies]
#bootloader = "0.9"
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = "0.14.2"
pic8259 = "0.10.1"
pc-keyboard = "0.5.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
```
(commented the `bootloader = "0.9"` here)
`/.cargo/config.toml`
```toml
[unstable]
# enable the unstable artifact-dependencies feature, see
# https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#artifact-dependencies
bindeps = true
```
`main.rs` and `build.rs` are unchanged.
