### ISSUE TITLE
Bootloader compilation fails

### ISSUE THREAD

**Issue by oblivisheee** [rust-osdev/bootloader#482]
<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/2131d03c-17cf-4886-8a6d-3e2f083d3a7b" />
When I add bootloader to Cargo.toml I get such thing. How do I fix this?

**Comment by Freax13** [comment]
What does your Cargo.toml looks like?

**Comment by oblivisheee** [comment]
@Freax13 
> What does your Cargo.toml looks like?
Cargo.toml
```toml
[package]
name = "merizo-os"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[target.aarch64-unknown-none.dependencies]
aarch64-cpu = "10.0.0"

[dependencies]
bootloader = "0.11.9"
cortex-a = "8.1.1"
tock-registers = "0.9.0"
uefi = { version = "0.33.0", features = ["qemu"] }
uefi-raw = "0.9.0"
```

.cargo/config.toml
```toml
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = ["-C", "link-arg=-Tconf/linker.ld", "-C", "target-cpu=cortex-a72"]
linker = "rust-lld"

```
